from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
ASSETS_DIR = ROOT_DIR / "assets"
MODELS_DIR = ROOT_DIR / "models"

PERSON_MODEL_PATH = MODELS_DIR / "person_detector" / "yolov8n.onnx"
GENDER_MODEL_PATH = MODELS_DIR / "gender_classifier" / "gender_mnv3.onnx"
GENDER_YOLO_MODEL_PATH = MODELS_DIR / "gender_classifier" / "gender_yolov8.onnx"
GENDER_CAFFE_PROTO = MODELS_DIR / "gender_classifier" / "gender_deploy.prototxt"
GENDER_CAFFE_WEIGHTS = MODELS_DIR / "gender_classifier" / "gender_net.caffemodel"
HELMET_MODEL_PATH = MODELS_DIR / "helmet_detector" / "yolov8n_helmet.onnx"

FACE_MODEL_PATH = MODELS_DIR / "face_detector" / "face_detection_yunet_2023mar.onnx"
EMOTION_MODEL_PATH = MODELS_DIR / "emotion_classifier" / "enet_b0_8_best_afew.onnx"

THUMBS_UP_PATH = ASSETS_DIR / "thumbs_up.png"
MALE_ICON_PATH = ASSETS_DIR / "male.png"
FEMALE_ICON_PATH = ASSETS_DIR / "female.png"
HELMET_GREEN_ICON_PATH = ASSETS_DIR / "helmet_green.png"
HELMET_RED_ICON_PATH   = ASSETS_DIR / "helmet_red.png"

CAMERA_INDEX = 1
CAMERA_BACKEND = 700
CAPTURE_WIDTH = 1280
CAPTURE_HEIGHT = 720
WINDOW_NAME = "SPAIS"

PERSON_INPUT_SIZE = 416
PERSON_CONF_THRESHOLD = 0.25
PERSON_IOU_THRESHOLD = 0.45
PERSON_CLASS_ID = 0

BYTETRACK_TRACK_HIGH_THRESH   = 0.45
BYTETRACK_TRACK_LOW_THRESH    = 0.10
BYTETRACK_NEW_TRACK_THRESH    = 0.50
BYTETRACK_MATCH_THRESH        = 0.80
BYTETRACK_SECOND_MATCH_THRESH = 0.50
BYTETRACK_MAX_AGE             = 30
BYTETRACK_MIN_HITS            = 2

SORT_MAX_AGE       = BYTETRACK_MAX_AGE
SORT_MIN_HITS      = BYTETRACK_MIN_HITS
SORT_IOU_THRESHOLD = BYTETRACK_MATCH_THRESH

GENDER_INPUT_SIZE = 64
GENDER_YOLO_INPUT_SIZE = 224
GENDER_LABELS = ("Male", "Female")
GENDER_CONF_THRESHOLD = 0.65

GENDER_BACKEND = "yolo"

USE_CAFFE_GENDER = False
USE_INSIGHTFACE_GENDER = True
INSIGHTFACE_MODEL_NAME = "buffalo_s"
INSIGHTFACE_DET_SIZE = 256
SHOW_AGE = True

HELMET_INPUT_SIZE = 256
HELMET_CONF_THRESHOLD = 0.2
HELMET_IOU_THRESHOLD = 0.45
HELMET_CLASS_NAMES = {0: "no_helmet", 1: "helmet"}
HEAD_CROP_RATIO = 0.30

ROI_POLYGON = [
    (320, 180),
    (960, 180),
    (960, 600),
    (320, 600),
]

CLASSIFIER_FRAME_STRIDE = 2
ANONYMISE_OVERLAY = False
SHOW_DEBUG_HUD = True

USE_OPENVINO_EP = False

SCENARIO2_CAPTURE_WIDTH = 640
SCENARIO2_CAPTURE_HEIGHT = 480

FACE_INPUT_SIZE = (320, 240)
FACE_CONF_THRESHOLD = 0.6
FACE_NMS_THRESHOLD = 0.3
FACE_TOP_K = 50
FACE_ALIGN_SIZE = 112

EMOTION_INPUT_SIZE = 224
EMOTION_LABELS = (
    "Anger", "Contempt", "Disgust", "Fear",
    "Happiness", "Neutral", "Sadness", "Surprise",
)
EMOTION_CONF_THRESHOLD = 0.30
EMOTION_HISTORY_LEN = 90
SHOW_EMOTION_BARS = False
